version: "3.3"
services:
    bot:
        image: avthorn/webex-reminders:latest
        build:
            context: .
        ports:
            - "5000:5000"
        tty: true
        stdin_open: true
        command: -m bot.bot
        secrets:
          - token
        depends_on:
          - redis
        restart: always
    watcher:
        image: avthorn/webex-reminders:latest
        build:
            context: .
        tty: true
        stdin_open: true
        restart: always
        command: -m bot.watcher
        secrets:
        - token
        depends_on:
        - redis
    redis:
        image: redis:6.2.1
        restart: always
        command: ["redis-server", "--appendonly", "yes"]
        ports:
            - "6379:6379"  # Redis Port
        volumes:
          - redis-data:/data
secrets:
    token:
        file: secrets.json
volumes:
    redis-data: